# Generated by Django 5.0.6 on 2024-05-25 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animal_created_at_animal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='photos/news/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='animal',
            name='facts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to='photos/animals/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='info',
            field=models.TextField(),
        ),
    ]
