# Generated by Django 5.0.6 on 2024-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_alter_employee_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='placequarter',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
