# Generated by Django 5.0.6 on 2024-05-26 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_new_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='portion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AddField(
            model_name='promo',
            name='first_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 19, 50, 47, 347188)),
        ),
        migrations.AddField(
            model_name='promo',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 19, 50, 47, 347188)),
        ),
    ]
