# Generated by Django 5.0.6 on 2024-05-26 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_food_portion_food_time_promo_first_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='tickets', to='zoo.client'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='first_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promo',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
