# Generated by Django 5.0.6 on 2024-05-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_remove_client_tickets_ticket_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
