# Generated by Django 5.0.6 on 2024-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0013_ticket_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='places',
            field=models.ManyToManyField(null=True, related_query_name='employees', to='zoo.place'),
        ),
    ]
