# Generated by Django 5.0.6 on 2024-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0015_alter_animal_food_alter_employee_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='food',
            field=models.ManyToManyField(related_query_name='animals', to='zoo.food'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='places',
            field=models.ManyToManyField(blank=True, related_query_name='employees', to='zoo.place'),
        ),
    ]
