# Generated by Django 5.1.1 on 2024-09-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0020_ticket_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
