# Generated by Django 5.1.1 on 2024-09-17 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0021_ticket_count_alter_ticket_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('logo', models.ImageField(upload_to='photos/about/')),
                ('video', models.FileField(upload_to='photos/about/')),
                ('year_history', models.TextField()),
                ('certificate', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='photos/employees/'),
        ),
    ]
