# Generated by Django 5.1.1 on 2024-09-19 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0022_about_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='photos/adsBanners/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='photos/partners/')),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
