# Generated by Django 5.1.1 on 2024-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0024_aboutyearhistory_remove_about_year_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsbanners',
            old_name='image',
            new_name='imageSrc',
        ),
        migrations.AddField(
            model_name='adsbanners',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adsbanners',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
