# Generated by Django 5.1.1 on 2024-11-16 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0025_rename_image_adsbanners_imagesrc_adsbanners_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSetitngs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delay', models.IntegerField(default=5000)),
                ('isLoop', models.BooleanField(default=True)),
                ('showNavs', models.BooleanField(default=True)),
                ('usePagination', models.BooleanField(default=True)),
                ('autoSwitch', models.BooleanField(default=True)),
                ('stopOnMouseHover', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
